[package]
name = "token"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
soroban-sdk = { version = "21" }

[dev-dependencies]
soroban-sdk = { version = "21", features = ["testutils"] }
